#!/bin/bash
ip link set dev eth0 up
ip a a 192.168.80.129/25 dev eth0
ip link set dev eth1 up
ip a a 170.6.253.130/30 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

# DHCP Donc pas de RIP
ip route add default via 170.6.253.129

# Lancement du DHCP
service isc-dhcp-server start

iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

