#!/bin/bash
ip link set dev eth0 up
ip a a 192.168.80.129/25 dev eth0
ip link set dev eth1 up
ip a a 170.6.253.134/30 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

