#!/bin/bash
ip link set dev eth0 up
ip a a 192.168.80.129/25 dev eth0
ip link set dev eth1 up
ip a a 170.6.253.134/30 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

# DHCP Donc pas de RIP
 ip route add default via 170.6.253.133
 
# Lancement du DHCP
service isc-dhcp-server start
 
# NAT
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

# Serveur web
iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to-destination 192.168.80.251:80

# Bloquer le SSH depuis l'extérieur
iptables -t filter -A FORWARD -i eth1  -p tcp --dport 22 -j DROP
