#!/bin/bash
ip link set dev eth0 up
ip a a 170.6.253.129/30 dev eth0
ip link set dev eth1 up
ip a a 170.6.253.133/30 dev eth1
ip link set dev eth2 up
ip a a 170.6.253.1/29 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

