#!/bin/bash
ip link set dev eth0 up
ip a a 170.6.253.10/30 dev eth0
ip link set dev eth1 up
ip a a 170.6.253.25/30 dev eth1
ip link set dev eth2 up
ip a a 170.6.253.13/30 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

#iptables --policy FORWARD DROP
iptables -t filter -A FORWARD -o eth2 -j DROP

# Ping

iptables -t filter -A FORWARD -o eth2 -p icmp -j ACCEPT
iptables -t filter -A FORWARD -o eth2 -p udp --dport 80 -j ACCEPT
#iptables -t filter -A FORWARD -p udp --dport 53 -j ACCEPT
